name: 今日ものんびり明日ものんびり
description: Blogging about stuffs
meta_description: "生きているだけで素晴らしい白熊のゆるふわ日記"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "http://note.shirokuma89.dev"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Your Name"

# Disqus config
disqus-shortname: ""
