name: 今日は明日の昨日
description: 生きているって素晴らしい
meta_description: ""

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 
domain_name: "http://note.shirokuma89.dev"
google_analytics: "UA-XXXXXXXX-X"
plugins:
  - jekyll-notion
  - jekyll-paginate

permalink: /:year:month:day/

# Details for the RSS feed generator
url: ""
author: "shirokuma89dev"

# Disqus config
disqus-shortname: ""